# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QAbstractItemView

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 251, 211))
        self.groupBox.setObjectName("groupBox")
        self.label_ip = QtWidgets.QLabel(self.groupBox)
        self.label_ip.setGeometry(QtCore.QRect(10, 20, 58, 21))
        self.label_ip.setObjectName("label_ip")
        self.label_port = QtWidgets.QLabel(self.groupBox)
        self.label_port.setGeometry(QtCore.QRect(10, 50, 58, 21))
        self.label_port.setObjectName("label_port")
        self.label_device_address = QtWidgets.QLabel(self.groupBox)
        self.label_device_address.setGeometry(QtCore.QRect(10, 80, 111, 21))
        self.label_device_address.setObjectName("label_device_address")
        self.label_sensor_address = QtWidgets.QLabel(self.groupBox)
        self.label_sensor_address.setGeometry(QtCore.QRect(10, 110, 111, 21))
        self.label_sensor_address.setObjectName("label_sensor_address")
        self.label_cyclical_times = QtWidgets.QLabel(self.groupBox)
        self.label_cyclical_times.setGeometry(QtCore.QRect(10, 140, 111, 21))
        self.label_cyclical_times.setObjectName("label_cyclical_times")
        self.lineEdit_ip = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_ip.setGeometry(QtCore.QRect(130, 20, 113, 22))
        self.lineEdit_ip.setObjectName("lineEdit_ip")
        self.lineEdit_port = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_port.setGeometry(QtCore.QRect(130, 50, 113, 22))
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.lineEdit_device_address = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_device_address.setGeometry(QtCore.QRect(130, 80, 113, 22))
        self.lineEdit_device_address.setObjectName("lineEdit_sensor_address")
        self.lineEdit_sensor_address = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_sensor_address.setGeometry(QtCore.QRect(130, 110, 113, 22))
        self.lineEdit_sensor_address.setObjectName("lineEdit_sensor_address")
        self.lineEdit_cyclical_times = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_cyclical_times.setGeometry(QtCore.QRect(130, 140, 113, 22))
        self.lineEdit_cyclical_times.setObjectName("lineEdit_cyclical_times")
        self.pushButton_record = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_record.setGeometry(QtCore.QRect(10, 170, 111, 28))
        self.pushButton_record.setObjectName("pushButton_record")
        self.pushButton_stop = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_stop.setGeometry(QtCore.QRect(130, 170, 111, 28))
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget.setGeometry(QtCore.QRect(270, 10, 521, 211))
        self.tableWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tableWidget.setRowCount(10)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(31)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        self.pushButton_record.clicked.connect(self.record_on_click)
        self.pushButton_stop.clicked.connect(self.stop_on_click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Setting"))
        self.label_ip.setText(_translate("MainWindow", "IP"))
        self.label_port.setText(_translate("MainWindow", "Port"))
        self.label_sensor_address.setText(_translate("MainWindow", "Sensor Address"))
        self.label_device_address.setText(_translate("MainWindow", "Device Address"))
        self.label_cyclical_times.setText(_translate("MainWindow", "Cyclical Times"))
        self.pushButton_record.setText(_translate("MainWindow", "Record"))
        self.pushButton_stop.setText(_translate("MainWindow", "Stop"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Location"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Temperature"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Date"))
